apiVersion: v1
kind: Pod
metadata:
  name: write-read-pod
spec:
  containers:
  - name: writer
    image: busybox
    command: ["sh", "-c", "echo 'Hello World' > /mnt/shared/hello.txt && sleep 3600"]
    volumeMounts:
    - mountPath: /mnt/shared
      name: shared-storage
  - name: reader
    image: busybox
    command: ["sh", "-c", "tail -f /mnt/shared/hello.txt"]
    volumeMounts:
    - mountPath: /mnt/shared
      name: shared-storage
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: ebs-pvc
